### ISSUE TITLE
Add "swooshes" from mockups into the site

### ISSUE THREAD

**Issue by danielgolden** [newrelic/opensource-website#368]
Neglected to add them the first time around
<img width="1422" alt="Captura de Pantalla 2020-05-12 a la(s) 11 46 46 a  m" src="https://user-images.githubusercontent.com/812989/81715551-5b621e80-9446-11ea-8388-972abc16a177.png">

**Comment by kevinharry** [comment]
Good

**Comment by jpvajda** [comment]
Swooshes were removed from our global style good. closing as wont' do
