### ISSUE TITLE
Query parameters lost w/o the trailing slash

### ISSUE THREAD

**Issue by tangollama** [newrelic/opensource-website#413]
This link works as expected.
https://develop.d2pwh5nf8rvczf.amplifyapp.com/explore-projects/?tag=New%20Relic%20One%20Application

This one does not.
https://develop.d2pwh5nf8rvczf.amplifyapp.com/explore-projects?tag=New%20Relic%20One%20Application

It appears to be an Amazon/S3/Amplify issue. Is there a resolution?
https://github.com/jariz/gatsby-plugin-s3/issues/51

**Comment by jpvajda** [comment]
These both seem to work for me and prompt me to authenticate. 

![Screen Shot 2020-11-12 at 5 27 49 PM](https://user-images.githubusercontent.com/1395158/99012832-689eb980-250c-11eb-863a-2e759b60e95e.png)
