### ISSUE TITLE
Horizontal scroll bar on the home page

### ISSUE THREAD

**Issue by jbeveland27** [newrelic/opensource-website#435]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

There's an unexpected horizontal scroll bar on the home page of the site. Present on both the staging (v0.5.6) and production (v0.5.5).

![image](https://user-images.githubusercontent.com/6722433/84791241-56057000-afc0-11ea-830b-9af87befddd0.png)

**Comment by danielgolden** [comment]
Didn't mean to close this with my fork PR.
