### ISSUE TITLE
External Projects page has extra whitespace

### ISSUE THREAD

**Issue by jbeveland27** [newrelic/opensource-website#436]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Bottom of the External Projects page contains extra white space. Present on both the staging (v0.5.6) and production (v0.5.5).

![image](https://user-images.githubusercontent.com/6722433/84791525-b98f9d80-afc0-11ea-8837-be89fec9a5d4.png)

**Comment by danielgolden** [comment]
Unable to reproduce in v1.0.14
