### ISSUE TITLE
In the stats generation, don’t list bots as contributors

### ISSUE THREAD

**Issue by tangollama** [newrelic/opensource-website#450]
Check out the new Relic CLI. The fourth most contributors is a bot. Can we find a way to suppress that in the stats automation?

**Comment by melissaklein24** [comment]
These are the bots I know about: 

demotronbot
newrelicbot
nr-developer-toolkit
nr-it-invoices
nr-opsbot
nr-security-github
nr-toolsbot

**Comment by jpvajda** [comment]
This is no longer the case on the New Relic CLI but excluding bots is probably a good idea, however i'm not sure it's really that meaningful as bots are pretty useful contributors. :)

**Comment by jpvajda** [comment]
Closing as won't do.
