### ISSUE TITLE
Resolve the tagging delta b/w Infrastructure and NRI's

### ISSUE THREAD

**Issue by tangollama** [newrelic/opensource-website#459]
![Image 2020-06-17 at 9 09 10 AM](https://user-images.githubusercontent.com/929261/84914918-2d49ad00-b08a-11ea-95ad-5b1ce64fda32.png)

Reported by @thezackm

**Comment by jpvajda** [comment]
I'd think we'd just use the `New Relic Infrastructure` Tag, not sure what the difference is between these 2 filters.

https://opensource.newrelic.com/explore-projects?tag=New%20Relic%20Infrastructure
https://opensource.newrelic.com/explore-projects?tag=Infrastructure

**Comment by jpvajda** [comment]
I've cleaned this up. in the linked PR.
