### ISSUE TITLE
Snapshots are failing due to version changes

### ISSUE THREAD

**Issue by tangollama** [newrelic/opensource-website#476]
Because we're using jest snapshots and because the version number is written in the footer, it's almost a guarantee that a PR is going to fail the test step... making that step unreliable and useless.

We must refactor what we're snapshotting to exclude the version string or abandon the strategy.

**Comment by jpvajda** [comment]
@tangollama We removed the version id from the OSS Footer as we aligned all footers to one single component for Docs , Developer and OSS sites, I think this can be marked closed.
