### ISSUE TITLE
Broken link with non-"master" default branch

### ISSUE THREAD

**Issue by njvrzm** [newrelic/opensource-website#518]
## Description

A project repo I'm trying to add uses `main` for the default branch instead of `master`. This seems to mostly be fine, but the link generated for "Contributors Guide" at the bottom has `master` hardcoded.

## Steps to Reproduce

1. Create a repo with no `master` branch.
1. Follow the [getting started](https://github.com/newrelic/opensource-website#getting-started) instructions.
1. Follow the instructions to [contribute project data](https://github.com/newrelic/opensource-website/wiki/Contributing-Project-Data)
1. Navigate to the new project page.
1. Click the "Contributors Guide" link at the bottom of the page.
1. See a 404 😄

## Expected Behavior

The contributing link should point to the default branch. However, since it's probably not reasonable to check that at compile time, perhaps an option to specify the default branch in the `projects/<project-name>.json` file would work.

**Comment by tangollama** [comment]
Closed per #521
