### ISSUE TITLE
Chevrons for primary nav elements persist when expanding from mobile layout

### ISSUE THREAD

**Issue by djsauble** [newrelic/opensource-website#519]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Chevrons that appear next to the primary nav elements when you open the hamburger on mobile persist if you expand the screen without closing the hamburger.

## Steps to Reproduce

1. Shrink the width of the browser until the hamburger appears
2. Click the hamburger
3. Notice that the primary nav is shown with chevrons
4. Expand the width of the browser until we leave the mobile layout
5. Notice that the chevrons are still visible!

## Expected Behaviour

I expect the chevrons to disappear from the primary nav items when we're not in mobile layout.

## Your Environment

* Safari 13
* macOS 10.15.5

## Additional context

Screenshot of what the primary nav looks like at the end of the reproduce steps above.

<img width="1252" alt="Screen Shot 2020-07-01 at 12 19 30 PM" src="https://user-images.githubusercontent.com/186715/86283086-39a72d00-bb95-11ea-8c13-fae6a21abe1c.png">

**Comment by jpvajda** [comment]
This is fixed closing.
