### ISSUE TITLE
Spacing / alignment gets a bit off on Explore Projects page...

### ISSUE THREAD

**Issue by markweitzel** [newrelic/opensource-website#541]
On the Explore Projects page, the alignment of the buttons is a bit off based on the amount of text in the middle box. 
<img width="1867" alt="New Relic open source projects _ New Relic Open Source 2020-07-17 18-21-06" src="https://user-images.githubusercontent.com/522116/87936712-5088c300-ca61-11ea-83df-f4bcbf95bb57.png">

**Comment by jpvajda** [comment]
The alignment issue with buttons and text seems to be fixed now.
<img width="1309" alt="Screen Shot 2020-11-12 at 5 22 26 PM" src="https://user-images.githubusercontent.com/1395158/99012531-de565580-250b-11eb-81b8-ab3b694979bd.png">


It looks like the C agent is actually named C SDK
<img width="1283" alt="Screen Shot 2020-11-12 at 5 23 45 PM" src="https://user-images.githubusercontent.com/1395158/99012539-e3b3a000-250b-11eb-890e-2d4a057cf9cb.png">
