### ISSUE TITLE
Organizing a navigation/IA paradigm for landing pages

### ISSUE THREAD

**Issue by tangollama** [newrelic/opensource-website#555]
Pages like [this](https://opensource.newrelic.com/nerdpacks/) and [this](https://opensource.newrelic.com/layouts/) are bound to grow. They don't belong in the primary nav, but they ought to be accessible (maybe in the footer?). We need a strategy for this and then an implementation.

**Comment by jpvajda** [comment]
Maybe these both belong on the developer site? They seem more relevant to a developer who may be looking to build a nerdpack.

**Comment by jerelmiller** [comment]
It might be beneficial to put it on both. They serve different purposes though. On the open source site, these are great to highlight open source apps that we have built in-house. This really helps us show off our commitment to open source. On the flip side, these are also great references for devs looking to build their own custom nerdpacks, which is a great case for also showing them off on the dev site.

**Comment by jpvajda** [comment]
closing for now, we'll come back to this if it becomes a problem.
