### ISSUE TITLE
On mobile, the global nav (top 40ish pixels) experience is different from developer.newrelic.com

### ISSUE THREAD

**Issue by tangollama** [newrelic/opensource-website#556]
The open source site needs to match the developer site experience.

![IMG_0797](https://user-images.githubusercontent.com/929261/88218379-f8eb8280-cc2d-11ea-8197-07d44518ce1e.PNG)
![IMG_0798](https://user-images.githubusercontent.com/929261/88218386-fbe67300-cc2d-11ea-813b-6669e88df564.PNG)

cc: @danielgolden

**Comment by jpvajda** [comment]
This should be fixed with our global header component implementation.
