### ISSUE TITLE
Buttons have lost their :hover, and :active state styles

### ISSUE THREAD

**Issue by danielgolden** [newrelic/opensource-website#565]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description
When you hover or click on a button, there are no longer any custom hover and active styles being applied to it.

[NOTE]: # ( Describe the problem you're encountering. )

## Steps to Reproduce
1. Navigate to [any project page](https://opensource.newrelic.com/projects/newrelic/nr1-datalyzer)
2. hover over either of the buttons at the top of the right column
3. Notice how there are no style changes during the `:hover` or `:active` states.

## Expected Behavior
I expected the following a subtle animation to be applied to the button on hover and active states using the below styles:

https://github.com/newrelic/opensource-website/blob/4e9be364c719257414fe4a6789fe0761821aabc8/src/components/styles.scss#L236-L245

## Your Environment

* Browser name and version: Chrome 84.0.4147.89 (Build oficial) (64 bits)
* Operating System and version: MacOS Catalina 10.15.5

**Comment by jpvajda** [comment]
This looks to be fixed, I see hover effects on these buttons now @danielgolden
