### ISSUE TITLE
Align the OSS Site Footer to look and feel more like the DevSite Footer

### ISSUE THREAD

**Issue by jpvajda** [newrelic/opensource-website#610]
Our goal is to align the OSS Site Footer as close as possible to the DevSite Footer so the look and feel is similar across sites. 

### Considerations

- Remove OSS page Navigation from the footer 
- Treat the standards link similar to how we present terms in the devsite footer. (select a new font for standards)
- Add a site version id to the devsite. (this should be automatically generated for both sites, if not we should fix that)
- Move the copyright and position it next to the OSS logo
- use the edit this page icon for the edit the page functionality remove the button styling
- use the create issue icon for the edit this page functionalityy, remove the button styling

### Current Dev Site Footer

![Screen Shot 2020-08-18 at 5 52 04 PM](https://user-images.githubusercontent.com/1395158/90576469-911c4f00-e17b-11ea-986a-9d2f41d326eb.png)

### Current OSS Site Footer

![Screen Shot 2020-08-18 at 5 52 13 PM](https://user-images.githubusercontent.com/1395158/90576479-97aac680-e17b-11ea-953e-8bc2c74c6c8f.png)

**Comment by jpvajda** [comment]
@djsauble Any opinions?

**Comment by djsauble** [comment]
I believe the [Standards](https://opensource.newrelic.com/standards) page on the open source site is only accessible through the footer nav, so we should leave it there so as not to orphan it.

I like the version identifier, tbh. It makes the website look more like a product than just a regular website, I think it's good for developers to see we treat it seriously in that way. We do a similar release process for the developer site too, so we should be able to pull the version identifier over too.

All of your other suggestions seem great.

**Comment by jpvajda** [comment]
@djsauble then it be cool to do the version the devsite as well. also I though the standards page could be like the terms in the devsite footer. so it still be there. Maybe a different icon for it.

**Comment by jpvajda** [comment]
Closing as this work will be done in MMF 5 of the Docs Site Migration.
