### ISSUE TITLE
Update a list of projects to community-plus

### ISSUE THREAD

**Issue by tangollama** [newrelic/opensource-website#620]
Move the following projects to an ossCategory of community plus.

- [ ] go-agent
- [ ] infrastructure-agent
- [ ] newrelic-dotnet-agent
- [ ] newrelic-python-agent
- [ ] newrelic-ruby-agent
- [ ] node-newrelic
- [ ] newrelic-java-agent
- [ ] infrastructure-bundle
- [ ] java-log-extensions
- [ ] newrelic-logenricher-dotnet
- [ ] newrelic-monolog-logenricher-php
- [ ] newrelic-winston-logenricher-node
- [ ] node-newrelic-aws-sdk
- [ ] node-newrelic-koa
- [ ] node-newrelic-mysql
- [ ] node-newrelic-superagent
- [ ] nri-apache
- [ ] nri-cassandra
- [ ] nri-consul
- [ ] nri-couchbase
- [ ] nri-discovery-kubernetes
- [ ] nri-docker
- [ ] nri-ecs
- [ ] nri-elasticsearch
- [ ] nri-f5
- [ ] nri-flex
- [ ] nri-haproxy
- [ ] nri-jmx
- [ ] nri-kafka
- [ ] nri-kube-events
- [ ] nri-kubernetes
- [ ] nri-memcached
- [ ] nri-mongodb
- [ ] nri-mssql
- [ ] nri-mysql
- [ ] nri-nagios
- [ ] nri-nginx
- [ ] nri-oracledb
- [ ] nri-postgresql
- [ ] nri-prometheus
- [ ] nri-rabbitmq
- [ ] nri-redis
- [ ] nri-snmp
- [ ] nri-statsd
- [ ] nri-varnish
- [ ] nri-vsphere
- [ ] nri-winservices
- [ ] aws-log-ingestion
- [ ] k8s-metadata-injection
- [ ] k8s-webhook-cert-manager

**Comment by jpvajda** [comment]
This looks done. closing.
