### ISSUE TITLE
Anchor links in oss-category are broken when navigating from another page

### ISSUE THREAD

**Issue by prototypicalpro** [newrelic/opensource-website#635]
[note]: # ' ^^ Provide a general summary of the issue in the title above. ^^ '

## Description

After navigating from any project page to the `oss-category` page, the category anchor links on the left side of the page redirect to `opensource.newrelic.com/#<category>` instead of the intended `opensource.newrelic.com/oss-category/#<category>`. This problem only occurs when using the anchor links _after_ navigating to `oss-category` from another page, and refreshing the page fixes the issue.

## Steps to Reproduce

1. Navigate to any project page (ex. https://opensource.newrelic.com/projects/newrelic/c-dt-example).
2. Click on the category for that page, located under the `View Repo` and `Edit page` buttons.
3. Attempt to use the category anchor links on the left.

## Your Environment

[tip]: # ' Include as many relevant details about your environment as possible. '

This issue was reproduced in the following environments:
- Chrome 64bit 85.0.4183.102 on MacOS 10.15.6
- Safari 13.1.2 on MacOS 10.15.6

**Comment by DamonHolland** [comment]
I have submitted a PR that should solve this issue if you reach the oss-projects page from a project page. If there any other occurrences where you are redirected to the oss-projects page, there needs to be a / following the link for the anchor links to work in its current state. There may be a better way to solve this issue universally, but I believe this will work for now.
