### ISSUE TITLE
NewRelic as a Heroku resource fails to load data in Safari

### ISSUE THREAD

**Issue by sighmon** [newrelic/opensource-website#643]
## Description

When viewing NewRelic as a Heroku resource in Safari, I can no longer see any data.

## Steps to Reproduce

1. Visit heroku.com
1. Tap `Installed add-ons > New Relic APM`
1. It tries to load https://one.newrelic.com/launcher/apm-nerdlets.application-index?pane=<ID>&platform[accountId]=<ACCOUNT>&platform[timeRange][duration]=1800000&platform[$isFallbackTimeRange]=true

## Expected Behavior

1. The page loads and I see my data.

## Relevant Console output

`XMLHttpRequest cannot load https://staging-insights-collector.newrelic.com/v1/accounts/<ACCOUNT_ID>/events due to access control checks.`

## Your Environment

- Browser name and version: Safari 14.0 (15610.1.28.1.9, 15610)
- Operating System and version: macOS 10.15.7

## Additional context

![broken](https://user-images.githubusercontent.com/314298/95007581-d972cc00-0658-11eb-94ab-c072368e6714.jpg)

**Comment by jpvajda** [comment]
@sighmon is this problem occurring in another browser?

**Comment by jpvajda** [comment]
I was able to get to the Heroku login page using Firefox.

**Comment by sighmon** [comment]
@jpvajda Yes, I can load the page in Firefox `82.0.3`

**Comment by jpvajda** [comment]
@sighmon thanks for confirming, so it sounds like an issue specific to Safari.

**Comment by jpvajda** [comment]
I'm trying to find out who supports our Heroku offering to report this issue.

**Comment by sighmon** [comment]
@jpvajda Is it really just limited to Heroku pages?

**Comment by jpvajda** [comment]
@sighmon I suspect not, I'm wondering if it's just an issue with the Safari browser, can you access `https://one.newrelic.com/launcher/apm-nerdlets.application-index?pane=&platform[accountId]=&platform[timeRange][duration]=1800000&platform[$isFallbackTimeRange]=true` on Safari, not using the link from Heroku?

**Comment by sighmon** [comment]
@jpvajda No I can't... same errors.

**Comment by jpvajda** [comment]
@sighmon I tested this URL on Safari Version 14.0.2 (15610.3.7.1.10, 15610) and it loaded OK for me.  Maybe try dumping your cache / cookies on safari and also update it if you haven't done so recently.

**Comment by jerelmiller** [comment]
Hey @sighmon! Taking a look at your screenshot above, it appears that maybe you have a security setting in your browser that might be blocking communication with our New Relic services. That `entity-search` call getting blocked looks suspect to me. Could you try tweaking the security settings in Safari and see if maybe that helps?

If you are still experiencing the same issue, we'll have you chat with product support as they'd be able to direct this to the team that owns that UI to investigate further. Let us know what happens!

**Comment by sighmon** [comment]
@jpvajda @jerelmiller Sorry, my mistake - I'd forgotten I had Better installed. https://better.fyi

**Comment by jerelmiller** [comment]
@sighmon no worries! Glad thats all it was!!
