### ISSUE TITLE
bump nr1-community components to Stable version

### ISSUE THREAD

**Issue by jpvajda** [newrelic/opensource-website#644]
https://www.npmjs.com/package/@newrelic/nr1-community/v/1.3.0-alpha.2

https://github.com/newrelic/nr1-community#readme

As part of the release of nerdstorage vault, we added the new components to the Nr1-community library. They are currently in alpha and we'll want to bump them to stable after nerd days.

**Comment by siddharthdeo99** [comment]
Can you explain this issue?

**Comment by jpvajda** [comment]
@siddharthdeo99 Sure thing. The  PM package linked in the issue in alpha release, and we'll want to bump it to a stable version. 

cc: @devfreddy

**Comment by jpvajda** [comment]
This is following our normal process for latest, stable and next. so closing as it 1.3.0 will soon become the latest release.
