### ISSUE TITLE
The open telemetry maintainer list needs to be updated

### ISSUE THREAD

**Issue by tangollama** [newrelic/opensource-website#658]
https://opensource.newrelic.com/projects/open-telemetry

As with all organizations, individual contributors transition from roles, and the current list needs to be updated. 

cc: @melissaklein24 to follow up / assign the work.

**Comment by jpvajda** [comment]
@melissaklein24 is this something you are taking care of? the issue is pretty old, so I wasn't sure if it's on your radar.
