### ISSUE TITLE
Clicking "Edit Page" Returns 404 URL links to undefined

### ISSUE THREAD

**Issue by angelatan2** [newrelic/opensource-website#659]
## Description
On the webpage https://opensource.newrelic.com/projects/newrelic/newrelic-ruby-agent, there is an "Edit page" button on the right side of the page next to the View Repo.  When I clicked on that link, it returns a 404 as the edit button now is pointing to:` https://github.com/newrelic/opensource-website/blob/develop/undefined`

## Steps to Reproduce
Click on the "Edit page" link for this page. 

## Expected Behavior
Allows me to edit and link to the correct repo for the page.

## Your Environment
Chrome

## Additional context

This seems to be occurring on new project pages being added to the OSS site as well.

**Comment by jpvajda** [comment]
@devfreddy / @tangollama Do you have any ideas why this one page edit button isn't linking to the right location? Other pages seem to work fine.

**Comment by jpvajda** [comment]
@jerelmiller I checked into this problem and I didn't see anything wrong with the code for the edit button, However I'm wondering if it's a repo setting, as it seems to only impact 2 repos at this moment:

https://github.com/newrelic-experimental/quickstarts

https://github.com/newrelic/newrelic-ruby-agent

**Comment by DamonHolland** [comment]
The issue seems to be related to the "slug" in newrelic-newrelic-ruby-agent.json.

Currently, The value is "newrelic-ruby-agent", while the corresponding .mdx is named "newrelic-newrelic-ruby-agent". The same issue may be occurring for the https://github.com/newrelic-experimental/quickstarts button as well.

**Comment by jpvajda** [comment]
@DamonHolland thanks for pointing that out!!  Would you be interested in submitting a fix for it? The project is opensource, so feel free if you want to help out to make the change an file a PR and I can code review it. 😃 , if not no worries!

**Comment by DamonHolland** [comment]
Alright, I will go ahead and try. This is my first open source contribution! I Just wanted to state what I thought the problem was in case I had issues on my end.

**Comment by jpvajda** [comment]
@DamonHolland cool! Give it shot  and if you need help we are here  to assist.
