### ISSUE TITLE
Add a link to Careers in our DECO Website Global Footer and link to our Careers page

### ISSUE THREAD

**Issue by angelatan2** [newrelic/opensource-website#663]
## Summary
Add a "Career" link to our Open Source, Dev Site and Docs Site websites to encourage people who are interacting with these different site to apply if they are interested in working for New Relic

## Desired Behavior

- Careers Link to https://newrelic.com/about/careers
- Careers is available on all 3 sites: Open Source, Dev Site and Docs Site websites
- Careers is added to the global theme footer component 

## UI 

- Place Careers in the footer as the 1st item.

![image (1)](https://user-images.githubusercontent.com/1395158/100802473-caa15f00-33e6-11eb-9bba-ecf13043e52b.png)

**Comment by jerelmiller** [comment]
Hey @angelatan2 this is a great idea! I'm looking at that careers page right now, but searching doesn't seem to do anything with the URL. Do you know if there is an easy way to use the URL to either pre-fill that input or go to the filtered view? If not, it might be a bit difficult to properly link to that careers page and pre-fill the field. Any help would be appreciated!

**Comment by angelatan2** [comment]
Not that I know off (i too scanned the source but could see how the field is populated).   Could you askIT,  and cc me so I can help push this effort.

**Comment by angelatan2** [comment]
Hi Jerel,  
Here is a link to use: https://jobs.jobvite.com/newrelic/search?c=&l=&q=Open%20Source.  The link will take us to jobvite with the open source positions listed.  Could we give this a go?

**Comment by jerelmiller** [comment]
cc @jpvajda on prioritization. I've moved this onto our board into "proposed" so we can chat about this in standup.

**Comment by jpvajda** [comment]
@jerelmiller We should probably add this nav element to the global header for all sites I assume.

**Comment by jpvajda** [comment]
We confirmed that the request was just for the open source site header, and the question is it better in the global footer?

**Comment by jpvajda** [comment]
I am going to follow up with @angelatan2 on a few questions about what the expectations are with how this needs to work:

`Link to https://newrelic.com/about/careers with the search field completed "Open Source". That is how FSO managers have been tagging our job descriptions.`

**Comment by jpvajda** [comment]
PR'd to the gatsby theme https://github.com/newrelic/gatsby-theme-newrelic/pull/163

**Comment by jpvajda** [comment]
PRS for each site to update to the lastest theme:

Dev Site: https://github.com/newrelic/developer-website/pull/1013
Docs Site: https://github.com/newrelic/docs-website/pull/354

**Comment by jpvajda** [comment]
@angelatan2 This is now available on all sites in our global footer.

**Comment by angelatan2** [comment]
Thank you team!! Awesome!
