### ISSUE TITLE
Integrating NR with Custom External Application

### ISSUE THREAD

**Issue by pabrahamusa** [newrelic/opensource-website#667]
I am still trying to understand what opensource-website is for , so apologies for basic questions.  I want to use some of the NewRelic charts components inside my kubernetes based external app running in Apache SuperSet.  The data can be pulled by superset and I can pass it to the NR based charts and other NR components to render on my external app. Is this possible with opensource-website.  I have NR subscription  and I use many NR based custom app running inside one.newrlic.com however that will not allow any external app to include NR components anyways.

**Comment by jpvajda** [comment]
@pabrahamusa thanks for the question. The New Relic OpenSource site provides all the repos that are part of our open source community. You are free to use any of the projects to build on New Relic as they are all licensed under the MIT license. 

For building chart components, you may want to check out our developer site for [building custom apps on New Relic](https://developer.newrelic.com/build-apps)

and also review the section on our [SDK](https://developer.newrelic.com/explore-docs/intro-to-sdk) the section on Visualization components may interest you.

Finally our [Forum](https://discuss.newrelic.com/) is a great place to find information on building on New Relic.

I hope that helps!
