### ISSUE TITLE
Typo on the section Instrumentation projects in https://opensource.newrelic.com/

### ISSUE THREAD

**Issue by mlennard-utn** [newrelic/opensource-website#675]
[note]: # ' ^^ Provide a general summary of the request in the title above. ^^ '

## Summary
There's a typo on the section Instrumentation projects, it says "Tutone" instead of "Tutorials" on the image. 
![image](https://user-images.githubusercontent.com/39415012/103778632-48bdda80-5011-11eb-8fb3-584aa14b449e.png)

[note]: # ' Provide a brief overview of your feedback. '

## Link to Page
https://opensource.newrelic.com/
[tip]: # ' Please provide the URL. '

**Comment by jerelmiller** [comment]
Hey @mlennard-utn! It does indeed look like this is intentional. That points at [this project](https://github.com/newrelic/tutone) which has been named "Tutone". Thanks for checking in!
