### ISSUE TITLE
use available brand icons for New Relic agents when applicable

### ISSUE THREAD

**Issue by zstix** [newrelic/opensource-website#686]
## Summary
[The list of New Relic instrumentation](https://opensource.newrelic.com/instrumentation/) shows that the majority of the official New Relic agents don't have a logo (see screenshot). The grid of cards with the same logo could make it hard to find what you're looking for.

## Possible Solution
Perhaps we can use each language's logo for these. It would help this page feel a little more interesting and provide more value to a user as these branded icons are recognizable. 

### Acceptance Criteria 

- [ ] When applicable show the correct brand icon for any instrumentation project that has a corresponding icon.
- [ ] For example, all apache projects would use the apache icon found[here](https://github.com/newrelic/docs-website/blob/develop/src/%40newrelic/gatsby-theme-newrelic/icons/logo/apache.js)
- [ ] If a branded icon isn't available continue to use the generic box icon
- [ ] The goal is to replace the generic box icon (_when applicable_) with the correct brand icon if available in our [icon directory](https://github.com/newrelic/docs-website/tree/develop/src/%40newrelic/gatsby-theme-newrelic/icons/logo)

## Additional context
![Screen Shot 2021-01-22 at 11 06 44 AM](https://user-images.githubusercontent.com/1946433/105534588-93428680-5ca2-11eb-8331-4597904cc5e6.png)

**Comment by jpvajda** [comment]
common language Logo files are available here: https://github.com/newrelic/docs-website/tree/develop/src/%40newrelic/gatsby-theme-newrelic/icons/logo

**Comment by Nitesh-Singh-5** [comment]
I want to work on this issue

**Comment by jpvajda** [comment]
@Nitesh-Singh-5 we'd love for you to contribute this feature, let us know how we can assist. cc @rudouglas  👋

**Comment by Nitesh-Singh-5** [comment]
can you suggest me ways to started ?

**Comment by rudouglas** [comment]
@Nitesh-Singh-5 delighted to hear you want to contribute. For this, as we don't currently have a centralized place for logos, you may need to copy them from [here](https://github.com/newrelic/docs-website/tree/develop/src/%40newrelic/gatsby-theme-newrelic/icons/logo) into the repo. I don't want to give you too much help in case you'd rather figure things out yourself, but feel free to reach out with any and all questions 😀

**Comment by jpvajda** [comment]
@Nitesh-Singh-5 To add to @rudouglas suggestions, I've clarified the acceptance criteria which is how Product managers help communicate what is expected from engineers. It's a great exercise for you to work through this and feel free to ask any clarifying questions or provide a draft PR if you have a solution you want us to review. And thanks for the interest in contributing!

**Comment by Deizuca** [comment]
@Nitesh-Singh-5 are you still working on this?

**Comment by rafaelcdelgado** [comment]
if @Nitesh-Singh-5  is not working on this I can help to Close this issue. Let me know

**Comment by jpvajda** [comment]
@rafaelcdelgado Feel free to take this on! We appreciate the contribution.

**Comment by rafaelcdelgado** [comment]
> @rafaelcdelgado Feel free to take this on! We appreciate the contribution.

Awesome, will work on this this week. Thanks.

**Comment by rafaelcdelgado** [comment]
Sorry guys, Got Covid but back on track...

**Comment by jpvajda** [comment]
@rafaelcdelgado no worries! I hope you are feeling better. 🙏

**Comment by pizzaz93** [comment]
There seems to be two approaches so far there's adding an icon.png to the repo, [Roku Example](https://github.com/newrelic/opensource-website/blob/4a317f4211caa42d0c81f1a0b37c4d28af12434d/src/data/projects/newrelic-video-agent-roku.json) and uploading user generated content, [iOS Example](https://github.com/newrelic/opensource-website/blob/4a317f4211caa42d0c81f1a0b37c4d28af12434d/src/data/projects/newrelic-video-avplayer-ios-tvos.json).
