### ISSUE TITLE
Decommission Google Analytics Snippet after Segment

### ISSUE THREAD

**Issue by zoezhou1113** [newrelic/opensource-website#698]
This a reminder that after the open source site is integrated with Segment, and Google Analytics is added to Segment as a destination, the Google Analytics snippet needs to be decommissioned, otherwise, Google Analytics may run into issues with receiving and process pageview data.

**Comment by jpvajda** [comment]
Relates to #737

**Comment by jpvajda** [comment]
This comment isn't clear to me: ``` the Google Analytics snippet needs to be decommissioned, otherwise, Google Analytics may run into issues with receiving and process pageview data.``` So I'll have to do some research into what steps need to be taken when segment is introduced, the Docs Site probably has a pattern we can look at.

**Comment by zoezhou1113** [comment]
John,

After your team has access to Segment, you can copy the Google Analytics
settings directly from another source. It's the icon that looks like a
download button next to the trash can.

[image: image.png]

Kind regards,
Zoe

Zoe Zhou
Web Analytics Manager
New Relic
Email: ***@***.***

**Comment by guggerjulien** [comment]
Vous pouvez lire mes codes ?

Le mer. 31 mars 2021 à 18:46, zoezhou1113 ***@***.***> a
écrit :

**Comment by jpvajda** [comment]
@zoezhou1113 so I think what you are saying is: we'd remove this from the gatsby-config.js file ```   gaTrackingId: 'UA-3047412-33',``` as it's no longer needed,  you can see how we removed it for the Docs Site [here](https://github.com/newrelic/docs-website/blob/3aa84141d89e6f0c18e16b89fd80963ad41285ed/gatsby-config.js)

Though this comment

> After your team has access to Segment, you can copy the Google Analytics
settings directly from another source. It's the icon that looks like a
download button next to the trash can.

makes me wonder: are we missing something in our Docs Site config? as I don't see a value for that. All I see is a [segmentwritekey](https://github.com/newrelic/docs-website/blob/3aa84141d89e6f0c18e16b89fd80963ad41285ed/gatsby-config.js#L152-L163)

**Comment by jpvajda** [comment]
I'm still working to understand what needs to be addressed in this issue so I'll speak to @zoezhou1113 about it as it relates to work we are doing in #737

**Comment by jpvajda** [comment]
closing as this is resolved in #737
