### ISSUE TITLE
Provide a page (or similar construct) for users to be able to view all media and entertainment-specific assets

### ISSUE THREAD

**Issue by adwetzelnr** [newrelic/opensource-website#722]
## Summary

For media and entertainment (video monitoring and ad monitoring) we will have about 20 libraries that we will open source.  (We have already open sourced five [https://opensource.newrelic.com/explore-projects?tag=Video](url))

In addition to the libraries themselves, there is documentation like:

-  the Data Model [https://docs.google.com/document/d/1ePxLuI4RFioFq_bc6amk28gj2ykt13CGPp6x2uGzEGg/edit](url)
-  the Graphical Workflow [https://docs.google.com/document/d/1ePxLuI4RFioFq_bc6amk28gj2ykt13CGPp6x2uGzEGg/edit](url)
- Dashboard Examples (with KPI, NRQL) descriptions
- a Media & Entertainment app

Having all of this as just tagged projects would not allow an interested user/customer to easily explore all telemetry/analytics/app options without bouncing around a bit

## Desired Behavior

To have a single place for a user/customer/Relic to go for Media and Entertainment assets such documentation, data model, etc. and link to the specific telemetry, analytics, and app repos.

## Possible Solution(

Create a page on the open source site that is easy to find and navigate to and will serve the function describe in 'Desired Behavior'

## Additional context

[tip]: # ' Why does this feature matter to you? What unique circumstances do you have? '

**Comment by jpvajda** [comment]
<img width="734" alt="Screen Shot 2021-03-19 at 1 52 06 PM" src="https://user-images.githubusercontent.com/1395158/111835233-4c47ca80-88ba-11eb-8584-46892679679f.png">

Thanks @adwetzelnr Why wouldn't we just follow the pattern already established with the use of Project categories,

https://opensource.newrelic.com/explore-projects?category=Community%20Plus

Why not add a category for media and entertainment then group all projects via this new category, you'll then have a centralized view of projects relating to that category type and you'd be following an existing design pattern.

you can the set the [ossCategory](https://github.com/newrelic/opensource-website/blob/cc20e7ef1f4d767582db6e09fbb43c605026a96a/src/data/projects/newrelic-nr1-github.json#L16) for each project that falls under media and entertainment. 


[oss-category-json](https://github.com/newrelic/opensource-website/blob/develop/src/data/oss-category/oss-category.json
)

If we take this approach we may want to consider added a new banner for this [category](https://github.com/newrelic/opensource-website/wiki/Open-Source-Category-Snippets)


I'm also going to cc @melissaklein24 on this as this would be the first time we'll be added a new category to the OSS Site so I just want to check that this approach doesn't cause any problems with the Opensource Office.

**Comment by adwetzelnr** [comment]
Thanks @jpvajda.

We already have (and use) a tag named 'Video'.  I could tag all the assets with 'Video' but I do feel that having a page or something similar would be a better experience for a user and do a better job of communicating all the assets and documentation available.

If creating a page is not desirable, is there a recommendation for creating the best experience around meta documentation, analytics/NRQL?  Perhaps a documentation repo and dashboards/nrql repo?
