### ISSUE TITLE
Add New Relic AVPlayer Agent for iOS and tvOS to OSS site

### ISSUE THREAD

**Issue by adwetzelnr** [newrelic/opensource-website#738]
## Project Title

New Relic AVPlayer Agent for iOS and tvOS

## GitHub URL

https://github.com/newrelic/video-agent-iOS

## New Relic Open Source Category

Video

**Comment by jpvajda** [comment]
@adwetzelnr What is it you are reporting here?  Are you requesting this be added as a project to the opensource site? If so here are instructions on how to do that if you'd like to make a contribution: https://github.com/newrelic/opensource-website/wiki/Contributing-Project-Data

**Comment by adwetzelnr** [comment]
@jpvajda I created the issue with the intention of subsequently submitting a PR for the json and mdx updates to create the project page.  Fate intervened and it's taking me longer than expected to make the changes and submit the PR.

**Comment by jpvajda** [comment]
@adwetzelnr awesome! When the PR is ready you can tag me on the review. Thanks for contributing!

**Comment by adwetzelnr** [comment]
@jpvajda just saw this after I submitted the PR so I didn't tag you.
