### ISSUE TITLE
Support Innovation <> DevEn In Product Help XP hand off

### ISSUE THREAD

**Issue by jpvajda** [newrelic/opensource-website#750]
The Support Innovation team is volunteering to take over the development of the In-product Help XP component  as there are some synergies with the work they are doing on the support side of that experience. In being so gracious in taking this over we'll want to walk them through the code, give them repo access, and provide a technical hand off.

### Timeline

- Sprint 4: May 11 - 25 : DevEn does the hand it off, we walk through the code base, transition it etc. 
- DevEn would continue to support the feature until July with Support Innovation ramping on it in June.
-  In July Support Innovation would kick off a project to improve the experience, aligning with the new Designs coming out of GPE. 
- DevEn would continue to support the `content-libary-service` and it's likely the improvements to the In-product Help XP, may require some service changes, still TBD, but we'd need to account for that potentially in August.

### Acceptance Criteria 

- [x] Discuss longer term vision to put this into a "right rail" like component that is now available in Nr1. 
- [x] disable the convention commit requirement on this repo
- [ ]  hand over the #space-squirrels Slack channel and rename to `help-nr1-help-xp`
- [x] add branch protection to the repo to ensure at least one sidekick review is provided before a merge can occur.
- [x] Schedule meeting the week of May 17 -- 21 
- [x] Invite Michel Losier , Michael Van Kleek
- [x] Walk through the In Product Help XP functionality for how docs content is rendered in the nerdlet
- [x] Walk through the architecture of the Docs-Library-Service

**Comment by jpvajda** [comment]
Next Step: meeting! 📆

**Comment by zstix** [comment]
Conventional commit requirements has been removed. I _think_ the only remaining tasks is to walk through the repository with the team and hand it off 🎉

**Comment by zstix** [comment]
After going through the technical review and making the final adjustments to the repository settings, I think we are able to safely close this issue out. We will continue to be available for questions (should any arise).
