### ISSUE TITLE
Project stats workflow is failing

### ISSUE THREAD

**Issue by nr-kkenney** [newrelic/opensource-website#755]
as seen [here](https://github.com/newrelic/opensource-website/actions/workflows/project-stats.yml), every run of the workflow since we enabled branch protections has been failing.

i think our approach will be to add something to the workflow to disable branch protections, similar to other workflows we have, rather than disabling branch protection on develop. In that case, we can refer to [this](https://github.com/newrelic/docs-website/blob/develop/.github/workflows/build-with-swiftype-content.yml) as an example.

update: saw this last night, we might be able to use: https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/, if one of those permissions enables us to remove / set branch protections.

update-2: we could probably simplify this by keeping the branch protection, but allowing the opensource bot to write to develop. we still get the security of preventing other contributors from writing directly, and we dont need a more complex workflow for temporarily disabling / enabling branch protection.

Acceptance Criteria:
- [ ] project stats workflow succeeds when run

**Comment by aswanson-nr** [comment]
I have removed the branch protection rules for now since they prevent the project from operating properly. No need to worry about this too much, since you still need to be a contributor to push commits to this repository.
As Kris said, there are multiple ways to resolve this and keep branch protection rules, we just need to have a discussion on which direction to take.

**Comment by jpvajda** [comment]
I'm gonna to test this out as I'm ✂️  a release of the OSS site today

**Comment by jpvajda** [comment]
fixed as per this release 🥳  https://github.com/newrelic/opensource-website/pull/765
