### ISSUE TITLE
Navigation controls hidden on mobile

### ISSUE THREAD

**Issue by aswanson-nr** [newrelic/opensource-website#758]
[note]: # ' ^^ Provide a general summary of the issue in the title above. ^^ '

## Description
After opening the nav on a mobile browser, the `X` button is hidden underneath the header.
<img width="341" alt="Screen Shot 2021-04-21 at 1 14 34 PM" src="https://user-images.githubusercontent.com/70179303/115616252-d6fa5b80-a2a4-11eb-90f1-c348b48adaff.png">

[note]: # " Describe the problem you're encountering. "

## Steps to Reproduce

[note]: # ' Please be as specific as possible. '
1. Go to the [OSS site](https://opensource.newrelic.com) on a mobile browser.
2. Click on the hamburger menu.
3. Notice that it clips underneath the header.

## Expected Behavior
The menu properly sits below the header and all buttons are accessible.

[note]: # ' Tell us what you expected to happen. '

## Additional context
The CSS to control this appears to have added, but never actually applied.
[Here](https://github.com/newrelic/opensource-website/commit/39ff171488ddf7df4557d93b3bdf46701fee4faa#diff-73a911c8ec65c995fea817bb73e24efd8ccca19e46a3d6a3d32de69f2204ce63R113-R119) you can see the styles, but they are commented out.
A [few commits later](https://github.com/newrelic/opensource-website/commit/373cd21a41d1743de0bb7de738f6c109693611b7#diff-73a911c8ec65c995fea817bb73e24efd8ccca19e46a3d6a3d32de69f2204ce63L118-L124) you can see the styles being removed.

**Comment by jpvajda** [comment]
Given the Mobile numbers are low on the OSS site I'm going put a P3 on this and backlog it for now.

<img width="1670" alt="Screen Shot 2021-04-21 at 2 41 35 PM" src="https://user-images.githubusercontent.com/1395158/115618523-0ebad080-a2b0-11eb-9d50-d7d8e5435e92.png">

**Comment by rudouglas** [comment]
#763 should fix this bug, I added a top in the css so that the menu buttons appear correctly on screens `<480px`:

<img width="416" alt="Screenshot 2021-04-28 at 12 54 37" src="https://user-images.githubusercontent.com/17122543/116399543-f2271700-a820-11eb-914f-991456ee5e15.png">
