### ISSUE TITLE
Project-Stats CI Workflow failing due to merge conflicts

### ISSUE THREAD

**Issue by rudouglas** [newrelic/opensource-website#766]
[note]: # ' ^^ Provide a general summary of the issue in the title above. ^^ '

## Description

[note]: # " Describe the problem you're encountering. "
The Project-Stats CI Workflow has been [failing since yesterday](https://github.com/newrelic/opensource-website/actions/workflows/project-stats.yml).  

The [first failure](https://github.com/newrelic/opensource-website/runs/2461056691?check_suite_focus=true) shows the error:
```
To https://github.com/newrelic/opensource-website
 ! [rejected]            master -> master (fetch first)
error: failed to push some refs to 'https://github.com/newrelic/opensource-website'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Error: Process completed with exit code 1.
```

Subsequent failures then all show a variety of merge conflicts, [for example](https://github.com/newrelic/opensource-website/runs/2462506389?check_suite_focus=true):

```
CONFLICT (content): Merge conflict in src/data/project-stats/newrelic-docs-website.json
Auto-merging src/data/project-stats/newrelic-developer-website.json
CONFLICT (content): Merge conflict in src/data/project-stats/newrelic-developer-website.json
Auto-merging src/data/project-stats/newrelic-demo-deployer.json
Auto-merging src/data/project-stats/newrelic-centurion.json
CONFLICT (content): Merge conflict in src/data/project-stats/newrelic-centurion.json
error: could not apply 64e6df4ed... chore(stats): updated project stats files
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
Error: Process completed with exit code 1.
```

**Comment by nr-kkenney** [comment]
this is not the first time this has failed for that reason. i think the workflow just needs a git pull when committing to the master branch.

also, im not sure if this qualifies as a bug since this is all internal code, and not product facing.

**Comment by jpvajda** [comment]
There are PRs associated with this, so closing
