### ISSUE TITLE
[Gatsby Cloud] DNS Changes & Documentation updates: OSS SIte

### ISSUE THREAD

**Issue by jpvajda** [newrelic/opensource-website#793]
### Related Issue

JIRA: `ELB-1676` `DONE`

https://github.com/newrelic/opensource-website/issues/757

###  Acceptance Criteria 

- [x] reach out to help-elb with a ticket to create cname
- [x] leave the connect to Amplify from the repository
- [x] move the DNS entry over to Gatsby Cloud --> need to work with ELB
- [x] also move the SSL cert --> need to work with ELB
- [x] Publish any documentation changes (troubleshooting, architecture, etc)

**Comment by jpvajda** [comment]
blocked on the issue with sub-domains on Fastly which Gatsby is working on for June. Ticket TBD.

**Comment by nr-kkenney** [comment]
ticket created for help-elb. id is `EKB-1676`.

**Comment by nr-kkenney** [comment]
opensource site is updated for gatsby cloud, documentation updated to match. closing.
