### ISSUE TITLE
Update OSS Site to Gatsby v3.8

### ISSUE THREAD

**Issue by jpvajda** [newrelic/opensource-website#803]
Due to the Gatsby Cloud bug  being resolved in this Gatsby issue(https://github.com/gatsbyjs/gatsby/issues/32042) we'll need to bump our version of Gatsby to [v3.8](https://www.gatsbyjs.com/docs/reference/release-notes/v3.8/)

### Acceptance Criteria 

- [x] Upgrade site to Gatsby v3.8
- [x] Test site visually 
- [x] Test if a PR builds 
- [x] fix issue with 🥕 s

### Bug

PRs fail to build on Gatsby Cloud sites that don't have  `gatsby 3.8` or is  using `gatsby-plugin-gatsby-cloud@2.8.1`

<img width="1030" alt="Screen Shot 2021-06-22 at 4 00 31 PM" src="https://user-images.githubusercontent.com/1395158/123172729-c7c99280-d43a-11eb-8fde-6c2fb4a3331f.png">

**Comment by rudouglas** [comment]
This seems to be building correctly, however, I noticed an issue with Carets in the filter section:
https://opensourcewebsitedevelop-ruairiupdategatsby38.gtsb.io/explore-projects
<img width="934" alt="Screenshot 2021-06-29 at 18 32 13" src="https://user-images.githubusercontent.com/17122543/123842264-7b81c500-d908-11eb-8e98-1614b8fe5b53.png">

Will need to dig into this further

**Comment by nr-kkenney** [comment]
i dont think i have enough knowledge to effectively speak to the problem @rudouglas mentioned, but ill write down my thoughts & research 🙈 

one weird thing i noticed when investigating this is that when you do a local / develop build, the site is fine & the icon is regularly sized. this issue is only encountered when doing a production build.

the image lives in the repo and has a specified height and width, but when loaded, we get an image that is missing those attributes:
in the repo:
```xml
<svg width="8" height="5" viewBox="0 0 8 5" fill="none" xmlns="http://www.w3.org/2000/svg">
<path fill-rule="evenodd" clip-rule="evenodd" d="M6.59998 0.5L3.99998 3.2L1.39998 0.5L0.599976 1.3L3.99998 4.6L7.39998 1.3L6.59998 0.5Z" fill="#8E9494"/>
</svg>
```
on page load:
```xml
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 8 5"><path fill="#8E9494" fill-rule="evenodd" d="M6.6.5 4 3.2 1.4.5l-.8.8L4 4.6l3.4-3.3-.8-.8z" clip-rule="evenodd"/></svg>
```

at the moment, im not sure where to look at account for this difference or how to address it.

**Comment by jpvajda** [comment]
We decided to pause on this upgrade and investigate if by upgrading the dev site, to 3.8 we'd see similar issues in CSS. it seems we don't use [the project search component](https://github.com/newrelic/opensource-website/blob/develop/src/components/ProjectSearchInput.js) anywhere else on our sites, so this may just be an OSS problem to resolve to be able to bump that site to Gatsby 3.8

Once we prioritize this, we can determine root cause and approach to fix this.

**Comment by jpvajda** [comment]
References to some troubleshooting Kris did

This was the issue: https://github.com/gatsbyjs/gatsby/discussions/17914
Which I got to from here I believe: https://github.com/gatsbyjs/gatsby/issues/8560

**Comment by jpvajda** [comment]
@LizBaker is swapping these custom 🥕s  to our standard 🥕 s
