### ISSUE TITLE
opensource category images should render correctly in dark mode

### ISSUE THREAD

**Issue by jpvajda** [newrelic/opensource-website#815]
when viewing the OSS category images in repos on github or in on the OSS site in dark mode, the images don't render well in dark mode.

### Examples 

- [nr1-github](https://github.com/newrelic/nr1-github/)
- [oss site category page](https://opensource.newrelic.com/oss-category/)

### screen shots 

![Screen Shot 2021-07-21 at 4 07 47 PM](https://user-images.githubusercontent.com/1395158/126566562-22c7c3e5-face-4ff7-a429-3f33675de629.png)

<img width="1014" alt="Screen Shot 2021-07-21 at 4 07 41 PM" src="https://user-images.githubusercontent.com/1395158/126566568-05489fb6-318d-4651-92b9-c080689874d8.png">

### Acceptance Criteria

- [ ] in dark mode OSS category images render correctly on Github and on the OSS Site.
- [ ] Don't break any existing image references to these category images as they are used in 100s of repos and are referenced into our repo templates and repo-linter checks.

**Comment by brammerl** [comment]
I'm going to try and work on this :)

**Comment by jpvajda** [comment]
i think this is unblocked now as the pr seems to have been merged.

**Comment by jpvajda** [comment]
I think this pr is also related https://github.com/newrelic/opensource-website/pull/816

**Comment by jpvajda** [comment]
I merged in #816. so closing
