### ISSUE TITLE
Add projects New Relic supports via GitHub Sponsors

### ISSUE THREAD

**Issue by aaronbassett** [newrelic/opensource-website#820]
## Summary

New Relic supports 50+ opensource maintainers, organisations, and projects via the [GitHub sponsors program](https://github.com/orgs/newrelic/sponsoring). We would also like to highlight these people on opensource.newrelic.com

## Possible Solution

On the homepage add an additional section below "Projects that we support". However due to the number of folks we sponsor I think we should style it the same as the "Explore our projects" panel, with 8 randomly selected folks shown on the homepage and a "view all" link which takes you to https://github.com/orgs/newrelic/sponsoring. 

The card for each person will be their avatar, name, and bio from GitHub.

## Additional context

I'm happy to take on this issue myself. I just didn't want to spring a PR on you first without discussing it 😄

**Comment by jpvajda** [comment]
I love this idea. 🚀

**Comment by Deizuca** [comment]
Happy to work in this if still needed

**Comment by jpvajda** [comment]
@Deizuca that be great! We'd love to accept this contribution. just drop a comment if you need any assistance.

**Comment by jpvajda** [comment]
@rudouglas was going to try to assist here.

**Comment by rudouglas** [comment]
Great work @Deizuca 🥳 https://opensource.newrelic.com/
