### ISSUE TITLE
Offically archive the nr1-quickstarts repo and 3rd party app `ETA: Jan 31`

### ISSUE THREAD

**Issue by jpvajda** [newrelic/opensource-website#847]
Relates to #833 

This is the follow up work to officially archive this repo and remove the app from the app catalog after we've given existing users a grace period to switch over to I/O for these needs. 

- [x] change deprecation message from Nov 1 - Jan 31 - @jpvajda 
- [x] Confirm that @kidk  has inventoried which dashboards are missing from the new quickstart library - @jpvajda 
- [x] ensure we have a plan to migrate these dashboards prior to the deprecation of this app - @jpvajda 
- [x] Remove the [QuickStarts app](https://github.com/newrelic/nr1-catalog/blob/master/globals.json) from the app catalog [folllowing these instructions](https://github.com/newrelic/nr1-catalog/wiki/New-Relic-One-App-Catalog-How-To-Guide#1-conduct-a-litmus-test-for-an-applications-health)
- [x] [Archive](https://opensource.newrelic.com/oss-category/#archived) the old quickstarts repo found [here](https://github.com/newrelic/nr1-quickstarts) https://github.com/newrelic/nr1-quickstarts/pull/58
- [x] [Archive](https://opensource.newrelic.com/oss-category/#archived) the this other old quickstarts repo found [here](https://github.com/newrelic/quickstarts-dashboard-library) https://github.com/newrelic/nr1-quickstarts/pull/58
- [x] shutdown the [githubpages site](https://newrelic.github.io/quickstarts-dashboard-library/#/)

**Comment by jpvajda** [comment]
We got some feedback that there are certain old quickstarts not yet available in the new quickstarts library so we've been asked to hold off the official deprecation of this application. 

the timing is still tbd so i'll take this for now. cc @thezackm

**Comment by jpvajda** [comment]
this PR was created to replace the missing dashboards https://github.com/newrelic/newrelic-quickstarts/pull/661

**Comment by jpvajda** [comment]
@kidk with the PR above, are we are OK with going ahead and archive this now?

**Comment by kidk** [comment]
:shipit: Thanks @jpvajda

**Comment by jpvajda** [comment]
i was gonna work on this ticket, but I don't think I have access to make a PUT request to artifact registry 😢

**Comment by jpvajda** [comment]
@LizBaker helped out.. and here the PR 

https://github.com/newrelic/nr1-catalog/pull/429

**Comment by jpvajda** [comment]
We are just waiting on the confirmation all users have been unsubscribed and all versions of the application have been removed from al environments.
