### ISSUE TITLE
[OSS site] Update all instrumentation to use tessen

### ISSUE THREAD

**Issue by LizBaker** [newrelic/opensource-website#879]
This ticket is blocked by https://github.com/newrelic/gatsby-theme-newrelic/issues/559

### Acceptance Criteria:

`note` 1st, verify if the site has any browser agent page actions that were not covered by the theme changes

- [ ] Bring in new version of the theme
- [x] Check all instances of the `instrumentation` prop and make sure it follows the correct tessen formatting (category is Title Case, event name is camelCase)
- [x] Check for any uses of the `useInstrumentedHandler` hook and make sure it’s formatted correctly for tessen
- [x] Check for any uses of the browser agent directly (window.newrelic.pageAction)
- [x] Update any documentation/wiki references to the browser events
- [x] Update any dashboards that may be using the old browser events (events should be listed in the wiki but may not be up to date. You can also run [this query](https://staging.onenr.io/0rVRVgAEvja) to get a list of currently firing browser actions ((some may be coming from theme components))

Here are some important dashboards to look out for:
* [[DevEn] Open Source Website](https://staging.onenr.io/0M8jqD3gdRl)
         * Every one of these dashboards seems broken, we should fix those as part of this effort.

**Comment by rudouglas** [comment]
I'm seeing the following error in Gatsby build but it doesn't seem to affect the sending of Tessen events:

```
warn Error persisting state: ({ location, env }) => ({
              path: location.pathname,
              env: env === 'production' ? 'pro...<omitted>...}) could not be cloned.
```

Removing this also doesn't change anything, `location` and `env` attributes are added to the event anyway, so i'm wondering if we actually need this?
