### ISSUE TITLE
[OSS] Add  gatsby-build-newrelic plugin to OSS site

### ISSUE THREAD

**Issue by jpvajda** [newrelic/opensource-website#882]
Related Bug: https://github.com/newrelic-experimental/gatsby-build-newrelic/issues/24

Following [the instructions here](https://www.gatsbyjs.com/blog/how-to-measure-gatsby-build-performance-with-new-relic/), add the  gatsby-build-newrelic plugin to the OSS site an install the quckstart for gatsby build for so we can measure the OSS sites build times more effectively. 

### Acceptance Criteria

- [x] Update Gatsby config to use gatsby build new relic
- [x] test on gatsby site for the PR branch
- [x] Setup up Env variables required for Gatsby build new relic on opensource develop site on Gatsby cloud
- [x] Setup up Env variables required for Gatsby build new relic on opensource main site on Gatsby cloud
- [ ] merge changes to develop branch
- [ ] merge develop to main
- [ ] install quickstart for gastby build on our developer enablement account
- [ ] delete opensource-website-gatsby-build-newrelic in Gatsby Cloud (as it was for testing) 
- [ ] delete test dashboard for opensource-website-gatsby-build-newrelic in New Relic
- [ ] look at some sweet dashboards

**Comment by jpvajda** [comment]
This ticket lead to some documentation updates in the plugin repo which @rudouglas did, and we found a bug: newrelic-experimental/gatsby-build-newrelic#24.

question: @rudouglas should we resolve this bug before I put this change on the develop branch? It seems it's just impacted the metrics dashboards, but I wanted to check before I proceed.

**Comment by rudouglas** [comment]
Ye lets hold off until we can get the metrics reporting @jpvajda

**Comment by rudouglas** [comment]
This is fixed now @jpvajda just remember we need the Environment variables in `develop` and `main` if we're going to merge the PR

**Comment by jpvajda** [comment]
@rudouglas you just made my list of ACs 🤣

**Comment by jpvajda** [comment]
Re-opening as the merge from develop to main failed  a check

https://github.com/newrelic/opensource-website/pull/888

**Comment by jpvajda** [comment]
dashboard can be [found here.](https://staging.onenr.io/0WBQ1yyy9Qx)
