### ISSUE TITLE
Missing local development steps

### ISSUE THREAD

**Issue by leslie-alldridge** [newrelic/opensource-website#913]
## Description

The readme suggests running:
```
yarn install
yarn start
```
And then the website should be running. In my case I see an error instead.

![image](https://user-images.githubusercontent.com/11302742/154827235-16e0240c-8b5d-46b3-8047-b8413625cd15.png)

## Steps to Reproduce

As a first time user of this project on windows 10 (you'll need to export env vars manually) run:

```
yarn install
yarn start
```

## Expected Behavior

Website to be running on port 8000

## Your Environment

- latest chrome
- windows 10

**Comment by jpvajda** [comment]
@roadlittledawn 👋

**Comment by roadlittledawn** [comment]
@leslie-alldridge looks like that error is coming from the [gastby-build-newrelic plugin](https://github.com/newrelic-experimental/gatsby-build-newrelic). specifically looks like maybe you need to add config options it expects? that error is coming from [this line](https://github.com/newrelic-experimental/gatsby-build-newrelic/blob/fc0c077dcdd1a51ec464bfde98d1ff5dcd9d60f1/utils/constants.js#L7) which is looking for `PLUGIN_OPTIONS.NR_LICENSE_KEY`.

here's an example of the opensource site's [config](https://github.com/newrelic/opensource-website/blob/d13b40a26ddaae95dd7df0f4d9e84ea58d9f19a3/gatsby-config.js#L190)
