### ISSUE TITLE
START SEGMENT IN NODE JS NOT WORKING.

### ISSUE THREAD

**Issue by Sparsh-Kumar** [newrelic/opensource-website#919]
I am making use of ```newrelic.startSegment()``` in Node JS, but I am not seeing any details regarding this transaction in my dashboard. The way I am using it is as follows.

```
class TestClass {
    constructor() {}
    runTestSecond() {
        nr.startSegment('runTestSecond', true, () => {
             console.log('In Run test second method ....');
        })
    }
}

const testClass = new TestClass();
testClass.runTestSecond();
```

I don't know why it is happening, am I doing something wrong here?

### Doc information (don't delete this section)

* https://opensource.newrelic.com/explore-projects/
* **OS**: Mac OS 10.15.7
* **Browser**: Chrome 99.0.4844.51
* **Device**: Unknown

**Comment by jpvajda** [comment]
@Sparsh-Kumar 👋 thanks for reporting this, but this repo is for the opensource website, so youll want to report this problem to your New Relic account manager, or file a support ticket, or look in discuss.newrelic.com for community support if you don't have official new relic support.
