### ISSUE TITLE
> <html> <body> <!-- Add a placeholder for the Twitch embed --> <div id="twitch-embed"></div> <!-- Load the Twitch embed JavaScript file --> <script src="https://embed.twitch.tv/embed/v1.js"></script> <!-- Create a Twitch.Embed object that will render within the "twitch-embed" element --> <script type="text/javascript"> new Twitch.Embed("twitch-embed", { width: 854, height: 480, channel: "monstercat", // Only needed if this page is going to be embedded on other websites parent: ["embed.example.com", "othersite.example.com"] }); </script> </body> </html>

### ISSUE THREAD

**Issue by ZarahSoraya** [newrelic/opensource-website#925]
> <html> <body>  <div id="twitch-embed"></div>  <script src="https://embed.twitch.tv/embed/v1.js"></script>  <script type="text/javascript"> new Twitch.Embed("twitch-embed", { width: 854, height: 480, channel: "monstercat", // Only needed if this page is going to be embedded on other websites parent: ["embed.example.com", "othersite.example.com"] }); </script> </body> </html>

_Originally posted by @ZarahSoraya in https://github.com/ZarahSoraya/Test/issues/13#issuecomment-1079816680_

**Comment by jpvajda** [comment]
closing..
